language: node_js
node_js:
- 0.1
notifications:
  email:
  - damon.oehlman@nicta.com.au
  irc: irc.freenode.org#rtc.io
env:
  global:
  - secure: V1fgQ60kCsrleQmXn7QOH/E+7q3svCybJzXy44cg+uSZ1CgNJrH+2iakx8sLnmyhbsbZvd0gCybl+5YMGO5uef7w6HkiwQew7XX6xaCJADQkvQEey+GJE9N5dTm9v4AG72Vl7+9nCmNDx52b1Pp7THsFQLtot8M/AqoKCB+B/js=
  - secure: zmRlNcx0DvHK0ftcZZgK9WgqWE1lOuXYWsqOHJu1Pp7ON6G+dspmISl4eeJ0eyElSDbtlAgP5PFb1ltnMw0dAVV9EIM8mY+5VL69FXOJAxXzznvpDhTgr7kA8J6gWn0pcLWdydlWaV5To4ZW/ediDeLMHQRSu8OpekU1/FlgnTk=
